.PHONY: clean All

All:
	@echo "----------Building project:[ PECLBachillerVelaDavid - Debug ]----------"
	@cd "PECLBachillerVelaDavid" && "$(MAKE)" -f  "PECLBachillerVelaDavid.mk"
clean:
	@echo "----------Cleaning project:[ PECLBachillerVelaDavid - Debug ]----------"
	@cd "PECLBachillerVelaDavid" && "$(MAKE)" -f  "PECLBachillerVelaDavid.mk" clean
